### ISSUE TITLE
crash at stop

### ISSUE THREAD

**Issue by CvH** [projectM-visualizer/projectm#111]
After several tests projectM (current master) crashs at stopping at kodi. It softcrashs kodi - not sure if the linked crashreport is helpful.

https://pastebin.com/ZKuKzctA

**Comment by deltaoscarmike** [comment]
Good news, this issue is fixed with this commit:
notspiff/visualization.projectm@4619d76d36e04e64a6072305b7f6dc851059376b

This issue was due to:
- Kodi doesn't save the openGL context during visualization shutdown. 
- projectM visualization plugin initialize a new openGL context during plugin shutdown :confused:

These events leads to a corrupted openGL context.

**Comment by deltaoscarmike** [comment]
Fix done in [xbmc/visualization.projectm@4619d76](https://github.com/xbmc/visualization.projectm/commit/4619d76d36e04e64a6072305b7f6dc851059376b)
