### ISSUE TITLE
Controls inaccessible on Nvidia Shield TV

### ISSUE THREAD

**Issue by snipsortega** [projectM-visualizer/projectm#135]
The app works fine, but I can no longer bring up the controls with the remote or game controller. I am running version 7.2 of the Shield TV OS.

**Comment by cheynebreyne** [comment]
I am having the exact same issue

**Comment by revmischa** [comment]
The mobile apps are not maintained as part of this project. You'll have to contact the author. Sorry.

**Comment by snipsortega** [comment]
Thank you. You wouldn’t happen to know who to contact would you? I purchased this on the Google Play store for the NVidia Shield TV set top box, not for mobile.

**Comment by devros42** [comment]
Did you ever find out who we should get in touch with?  Having the same issue with my shield.  From the Play Store if you click on the developer link it sends you to the GitHub repo.

**Comment by psperl** [comment]
Google broke the API for managing the controls when they released the newest android version.  It caused the overlay in apps like mine to stop responding to events.  They don't care about Android TV because it's so unpopular, so they don't mind making breaking API changes.  I can fix it by changing the app, which I've done, but there are a hundred other bugs I need to work out because of the new API level.  I'm just lazy and haven't found the time.

**Comment by psperl** [comment]
Just to be crystal clear, I am the original projectM author and am responsible for the mobile apps.  Mischa and some other great devs have taken over the open source stuff.  I'm aware of this issue, and am just busy and lazy and there are a lot of things to do to support all Google's new API level and app requirements.

**Comment by psperl** [comment]
Shoot me a mail at peter@sperl.com and I'll send you guys a test APK for testing.

**Comment by devros42** [comment]
Seems good to me.  Grooving out to some Rush with it right now :) 
Thanks for the quick turnaround.  One minor issue and a question.

When in the setting for Visual Duration if you hold the down key down to quickly scroll all the way down the app will crash.

Not sure if this is by design or not, but if you hit the dice button, sometimes it will stay locked on that preset and pressing the dice buttons or the arrows won't change the preset.  It seems to work ok after the preset has toggled on its own.
