### ISSUE TITLE
Drop features for maintainability

### ISSUE THREAD

**Issue by dzarda** [projectM-visualizer/projectm#188]
Feels like there's a lot of legacy baggage that strangles innovation. From my limited look at the project, the following areas appear to serve little purpose:

1. Native presets - each adds a new project to the tree which makes the thing more complex. Maybe we can keep just the "M with headphones"?
2. "Textures" are a concept that is unknown to me.
3. Some projects appear irrelevant:
  - projectm-wmp - some WinAPI
  - projectm-moviegen - C with SDL, seems a duplicate of projectm-sdl
  - projectm-wxvis
  - projectm-screensaver
  - maybe more...

**Comment by struktured** [comment]
@dzarda 

1. native presets - much more efficient and less clunky than using the milkdrop preset language, but perhaps they should be externalized outside the projectm main repo.

2. textures are essential to some traditional milkdrop v2 presets. I would not deprecate that without good reason.

3. 
 - projectm-moviegen is what it sounds like- tries to produce a motion video rather than a realtime rendering
 - projectm-wxvis/wmp is likely not terribly useful anymore
 - projectm-screensaver - don't know much about it but probably doesn't work anymore either

**Comment by revmischa** [comment]
NativePresets should be optional or externalized #99 
Send a PR!
