### ISSUE TITLE
Side-by-Side stereoscopic rendering

### ISSUE THREAD

**Issue by ghost** [projectM-visualizer/projectm#215]
This feature would modernize the projectM system. In my opinion, stereoscopic 3D would be an essential feature from projectM compared to legacy Milkdrop. It feels like we are chasing something that’s already been done a decade ago, however adding stereo vision would truly make this the most advanced visualization engine.

**Comment by revmischa** [comment]
c.f. https://github.com/projectM-visualizer/projectm/pull/201

**Comment by mancoast** [comment]
The support for multiple passes is a completed requirement, the viewport can be rendered with two passes and we can emulate space between eyes with viewport offset. This issue is about providing a stereoscopic project within the repo that demonstrates the new multiple pass renderer from https://github.com/projectM-visualizer/projectm/pull/201

**Comment by mancoast** [comment]
@hibengler do you have any nuggets of wisdom or code to share here?

**Comment by revmischa** [comment]
Would be sweet to have a club where they give people 3d glasses and project stereoscopic projectm for the music

**Comment by hibengler** [comment]
Well, it is a full application instead of a nugget.  I got it working in Linux,  struggling to get progecjtm, and the VR on iphone and android.


VR comes from a heavily edited version of Raylib.  Currently straight ahead, didn't compensate for eye separation.  But it looks cool.

Also instead of being true realistic VR- I like to make subtle differences to reality - map the left channel in one eye and the right channel in the other.  So have a vomit bucket nearby....

Open source is at http://open.killercool.com/cgi-bin/viewvc.cgi/opencvs/SilentRadiance/linux/

installation instructions from source is from
http://open.killercool.com/cgi-bin/viewvc.cgi/opencvs/SilentRadiance/linux/client/src/install.txt?view=log

If you twist my arm, I can put the binary up.   Runtime install is easier
xubuntu 18.04

This application is also available on apple and android - minus projectM, on the stores.

**Comment by hibengler** [comment]
Basically pass1is called once, and pass2 is called twice, once for each eye.  This could be used for other
points of view as well.

**Comment by mancoast** [comment]
i am seriously struggling to clone your repo at http://open.killercool.com/cgi-bin/viewvc.cgi/opencvs/SilentRadiance/

is it possible to access via svn or git?

**Comment by hibengler** [comment]
Sorry about that, I thought I did this months ago.

https://github.com/hibengler/SilentRadianceFillSnapshot_1.3n   - linux only.
Enjoy

**Comment by honestbleeps** [comment]
is there any chance this feature makes it to Oculus Quest, even as a sideloaded APK?  I'd love to see it on there!
