### ISSUE TITLE
No "M" settings menu!!!

### ISSUE THREAD

**Issue by fvdfgrgtg42etgfw** [projectM-visualizer/projectm#329]
Installed from source on Linux Mint 19.3 Xfce 64-bit

This means no settings, no nothing except presets in alphabetical order trying to listen to my voice through a disabled microphone. How do I open the damn settings menu in the latest version of projectMSDL? I initially assumed it's M, pressed M, and nothing happened. Tried every possible key combination and the only ones are P for Previous, N for Next, R for Random, Ctrl-Q for Quit, and some other weird stuff.

How am I going to tell it to listen to the computer's speakers and not the disabled microphone? (That's just my assumption that it defaults to mic because it was the default in previous "successful" install sometime in August/September.)

How am I going to automatically shuffle the visualizations so it's not a repeat every time?

I need actual help, not bureaucratic redirects, please. Don't try to kill this issue and fade my grievances into dust by redirecting to another issue, closing this one, and never actually answering anything. It's already been done for this topic several times before and it has never worked.

**Comment by revmischa** [comment]
There's no menu for projectMSDL, right now. Some support for drawing text in it needs to be added. This is a volunteer open source project, if you're unhappy with the quality you can be issued a full refund

You can see the list of key bindings here: https://github.com/projectM-visualizer/projectm#keyboard-controls
If you are building the latest source, try Cmd/Ctrl-I to switch audio input device. However your speakers are not an audio input device.

**Comment by kblaschke** [comment]
Rendering support was there (projectM actually does this), but is was buggy and the search menu crashed the application. Pull request #525 will fix this issue. After the fix, press F1 to show the help menu or press enter to start searching.

**Comment by kblaschke** [comment]
To answer some questions of the OP:

> How am I going to tell it to listen to the computer's speakers and not the disabled microphone?

If conmpiled against SDL 2.0.15 and earlier, it is not possible to capture desktop audio due to the fact SDL ignores PulseAudio "monitor" devices completely. icculus (Ryan C. Gordon) fixed this recently, and I've added a new SDL hint that enables monitor devices automatically when using SDL 2.0.16 and higher. If you compile from source, just check out the SDL2 sources, compile the latest master/release as a static library using CMake and use `-DCMAKE_PREFIX_PATH=path-to-sdl` while configuring projectM with CMake to point to your SDL install dir. It will then prefer monitor devices. In the app, you can cycle the device with `ctrl+i`. After reenabling the menu and text overlay as in my linked PR above, the application will briefly echo the device name in the center of the screen so you can see which device is used.

> How am I going to automatically shuffle the visualizations so it's not a repeat every time?

By default, the SDL app should randomly switch presets from the current "playlist", which is generated using the preset path in the settings and collecting all presets from the path including subdirs. There's a weighting by rating AFAIK, so if you rated some presets higher, they should be displayed more frequently. Besides that, you can press `r` to switch to a random preset. Press `space` to lock the current preset and disable automatic switching. With the menu reenabled, press `enter`to activate search mode and type text to filter presets, then use `up`/`down` to preview and `enter` to select a preset.

With the menu enabled, pressing `F1` will show a help text with the available hotkeys.
