### ISSUE TITLE
writeConfig needs enhancements

### ISSUE THREAD

**Issue by milkdropper** [projectM-visualizer/projectm#374]
The latest commit to master uses writeConfig (which has been around for years and is in use with QT). The issues with it I noticed:

- it will not write back comments.
- if the original config you loaded is is larger than the config you write back (because of comments), it write content to the start of the file without deleting the previous content. So the first half or more is the new config, and you still have remnants of the old config.

I can take this issue but others might be interested.

**Comment by kblaschke** [comment]
Noticed that too, bad if you want to have a list of preset paths to switch between for example.

`writeConfig()` should read an existing file, copy any blank lines and comments as-is and only change values on lines with a specific key. Inline comments (is possible?) should also be retained. Any keys not preset in an existing file can be appended to the end. then just overwrite the existing file with the new content, done.

Take the issue if you want, there's already plenty of other stuff to do for me.

**Comment by audreyspency** [comment]
I'm interested in the solution

**Comment by kblaschke** [comment]
No work done on this yet, but should be relatively straightforward to implement.

**Comment by kblaschke** [comment]
This issue was "solved" by completely removing the config file stuff and while at it, same for the settings struct. Now everything is passed by setters and leaves the configuration file stuff to the application, as the core library really shouldn't care about that.

The new SDL app already uses a different, more sophisticated file format. Other apps using projectM can store the settings in their own way.
