### ISSUE TITLE
Does this project support multiple view now.

### ISSUE THREAD

**Issue by eximpression** [projectM-visualizer/projectm#424]
About 2 years ago, I test to creat two context and want to render in two UIView on iOS device, it's crashed. And now, does it support render on multiple view now?

**Comment by revmischa** [comment]
Does libprojectM work on iOS? How?

**Comment by eximpression** [comment]
> Does libprojectM work on iOS? How?
search Everplay on App Store

**Comment by kblaschke** [comment]
The main issue with two projectM instances running in the same process is the OpenGL rendering context. If you have two UIView instances and both run in separate threads in the same process, this will definitely cause a crash. This means if you need two projectM instances in the same application, you must make sure to always call _all_ projectM methods from the _exact same thread_ that created the projectM instances in the first place. The only exception are the `addPCM*()` functions in the PCM class used to add audio samples. These are (mostly) safe to be called from a different thread.

This is an OpenGL limitation, and we can't do anything about this.

Besides this obvious limitation, there might be other data structures with static members that are shared between instances and cause more race conditions. But since OpenGL is already the limiting factor here, this won't fix anytime soon.
