### ISSUE TITLE
Better XDG_CONFIG_HOME support

### ISSUE THREAD

**Issue by Iiridayn** [projectM-visualizer/projectm#426]
I was excited when skimming the source and saw XDG support (I have _way_ too many (> 3) `.files` in my `~`) - but disappointed when I found the config file was not in my `$XDG_CONFIG_HOME` - which I leave unset so I can use the default location.

Per the spec (https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html - 5 min read for the whole thing):
> $XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. **If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.**

Emphasis mine.

**Comment by Iiridayn** [comment]
See https://github.com/projectM-visualizer/projectm/blob/d85d41b69c1c4c258baaeb587f4d8c72c33bff25/src/projectM-pulseaudio/qprojectM-pulseaudio.cpp#L188 for what I was looking at :).

**Comment by revmischa** [comment]
Feel free to open a PR with what you desire

**Comment by Iiridayn** [comment]
Sorry, ran out of energy working on the other bit - and it seems some of the other applications and library hard code the dot dir in `~`, so I'd have to understand the whole system much better than I could in a mere 16 hours. Just leave it open and maybe get to it someday.

I tried. I really tried.

**Comment by kblaschke** [comment]
I'd say this issue is now more related to the frontends, as the library will become less aware of such things and rely on the paths supplied by the integration. Makes more sense anyway, as every app has its own requirements.

The rewritten SDL frontend automatically uses `XDG_CONFIG_HOME` via POCO's configuration framework, internally by calling `Poco::Path::configHome()` or via `${system.configHomeDir}` in the configuration file, so no need for any additional code. On Windows, this will direct to the equivalent `%APPDATA%` dir.

Closing this here, as the library shouldn't be aware of that anymore.
