### ISSUE TITLE
A couple of questions about your project

### ISSUE THREAD

**Issue by ghost** [projectM-visualizer/projectm#45]
Hello hello! I have been using ProjectM for YEARS every day! I have a secondary PC that acts as a "stereo-server", with two smaller 19-21" inch screens on each side of my 40 inch screen, with ProjectM set to open on boot-up, its really beautiful! 

There hasn't been an update to ProjectM in a very long time on Arch Linux, I can't even remember when the last time was I saw an update for ProjectM... So I'm just wondering... Is that because you haven't made an official release in a while or perhaps it just hasn't been getting updated in the arch linux repositories? And can the iProjectM HD be ported to Linux or is there perhaps a "ProjectM HD"? It'd be really awesome if we had a similar plugin for Clementine if that is even possible.

The version in the Arch Linux "Community" repo is: 2.1.0-17
For the record I'm using Artix, which is OpenRC arch that shares a few repos with the official Arch.

Thank you for your time & especially for your work.

**Comment by kenny-w7** [comment]
Also, I am trying to compile ProjectM on Void Linux MUSL, I was wondering if you might be able to help me figure out what dependency I am missing:

https://pastebin.com/95ieEkBT

**Comment by revmischa** [comment]
iprojectM HD is just using the Cg shader framework from nvidia, which is super deprecated now. Work needs to be done to use GLSL for the shaders. It's non-trivial but it needs to be done at sompoint.

You can see the status of the downstream packaging on arch here: https://aur.archlinux.org/pkgbase/projectm-git/

It looks like you're trying to build the SDL version. if you use the very latest master from git and re-configure, does it work? It no longer builds the SDL version by default. Do you have libsdl2?

**Comment by revmischa** [comment]
Here, this should fix your compilation issue: https://github.com/projectM-visualizer/projectm/pull/42/commits/1dfe9daa484e306ac138db6ecd4314230c21e62a

I'll try to get it merged to master shortly

**Comment by revmischa** [comment]
Kenny - try out master now if you like. Does it build for you?

**Comment by kenny-w1** [comment]
Yep, it builds now! Thank you!

**Comment by revmischa** [comment]
Current version is 2.2.1
What's the exact error you're getting?
make[3]: Entering directory '/home/kzn/Compiles/projectm/src/projectM-sdl'
make[3]: *** No rule to make target 'all'.  Stop.
?
It sounds like it needs configuring. Try re-running ./autogen.sh and reconfigure?

**Comment by kenny-w1** [comment]
Can't get it to launch:
qt5ct: using qt5ct plugin
dir:/usr/local/share/projectM/config.inp 
reading ~/.projectM/config.inp 
qt5ct: D-Bus global menu: no
[projectM] config file: /home/kzs/.projectM/config.inp
Failed to open font /usr/share/projectM/fonts/Vera.ttf
Failed to open font /usr/share/projectM/fonts/Vera.ttf
[projectM] Allocating idle preset...
Loading preset idle://Geiss & Sperl - Feedback (projectM idle HDR mix).milk
[PresetFactory] path is Geiss & Sperl - Feedback (projectM idle HDR mix).milk
[PresetFactory] url is idle://Geiss & Sperl - Feedback (projectM idle HDR mix).milk
Segmentation fault

**Comment by kenny-w1** [comment]
Oh, looks like its launching now but its coming up with lots of errors.

**Comment by revmischa** [comment]
I haven't tried the qt5 version. Maybe you can figure out what's up? @deltaoscarmike any idea?
Just a report of "segmentation fault" isn't super useful, any more info?

**Comment by kenny-w1** [comment]
Don't know what else I can tell you, I can make it launch in sudo for some reason...

**Comment by revmischa** [comment]
Perhaps try launching with gdb or lldb and do a stack trace on the segfault?

**Comment by kenny-w1** [comment]
Not sure how to do that.... don't know what gdb or lldb are, sorry.

**Comment by deltaoscarmike** [comment]
It seems to be an installation issue:
Configuration is readed from ~/.projectM:
> reading ~/.projectM/config.inp

But fonts and/or presets are should be in /usr/share
> Failed to open font /usr/share/projectM/fonts/Vera.ttf

This inconsistency could be the source of this segfault

@kenny-w1, What parameters did you use for configure command ?
It would be very usefull if you can post your compile **and** run commands

**Comment by kenny-w1** [comment]
Alrighty, here are the outputs:
configure, configure --enable-qt --enable-ftgl, make
https://pastebin.com/vDkNcw5K

make install
https://pastebin.com/Htw4Yh15

**Comment by kenny-w1** [comment]
projectM-pulseaudio
qt5ct: using qt5ct plugin
dir:/usr/local/share/projectM/config.inp 
reading ~/.projectM/config.inp 
qt5ct: D-Bus global menu: no
[projectM] config file: /home/kzs/.projectM/config.inp
[projectM] Allocating idle preset...
Loading preset idle://Geiss & Sperl - Feedback (projectM idle HDR mix).milk
[PresetFactory] path is Geiss & Sperl - Feedback (projectM idle HDR mix).milk
[PresetFactory] url is idle://Geiss & Sperl - Feedback (projectM idle HDR mix).milk
Segmentation fault

and, as root:
projectM-pulseaudio
QStandardPaths: wrong ownership on runtime directory /run/user/1001, 1001 instead of 0
QStandardPaths: wrong ownership on runtime directory /run/user/1001, 1001 instead of 0
qt5ct: using qt5ct plugin
dir:/usr/local/share/projectM/config.inp 
reading ~/.projectM/config.inp 
qt5ct: D-Bus global menu: no
[projectM] config file: /root/.projectM/config.inp
[projectM] Allocating idle preset...
Loading preset idle://Geiss & Sperl - Feedback (projectM idle HDR mix).milk
[PresetFactory] path is Geiss & Sperl - Feedback (projectM idle HDR mix).milk
[PresetFactory] url is idle://Geiss & Sperl - Feedback (projectM idle HDR mix).milk
Segmentation fault
[kz-stereo .projectM]# projectM-pulseaudio
QStandardPaths: wrong ownership on runtime directory /run/user/1001, 1001 instead of 0
QStandardPaths: wrong ownership on runtime directory /run/user/1001, 1001 instead of 0
qt5ct: using qt5ct plugin
dir:/usr/local/share/projectM/config.inp 
reading ~/.projectM/config.inp 
qt5ct: D-Bus global menu: no
[projectM] config file: /root/.projectM/config.inp
[projectM] Allocating idle preset...
Loading preset idle://Geiss & Sperl - Feedback (projectM idle HDR mix).milk
[PresetFactory] path is Geiss & Sperl - Feedback (projectM idle HDR mix).milk
[PresetFactory] url is idle://Geiss & Sperl - Feedback (projectM idle HDR mix).milk
Segmentation fault

**Comment by kenny-w1** [comment]
projectM 2.1.0 from the arch linux repo works fine, not sure what I could be doing wrong.

For the record I have attempted to build projectM without ftgl, but the output above has ftgl & qt enabled, it appears whether ftgl is enabled or not makes no difference.

**Comment by revmischa** [comment]
@kenny-w1 does this help at all? https://github.com/projectM-visualizer/projectm/pull/68

**Comment by revmischa** [comment]
I believe a fix for this is merged. Please let us know if you continue to have issues
