### ISSUE TITLE
ProjectM Crash due to Corrupt Linked List

### ISSUE THREAD

**Issue by stevenswart** [projectM-visualizer/projectm#477]
20th March 2021

I have noticed occasional crashes while running ProjectM under Kodi. I am using OpenSUSE Tumbleweed, and my method is to run the kodi-x11 binary directly from a shell command-line, so that I can observe the output. I occasionally get a crash with the following output:

```
[PresetFactory] url is /usr/share/kodi/addons/visualization.projectm/resources/projectM/presets/presets_bltc201/Jess - Jess 3.milk

corrupted double-linked list (not small)
Aborted (core dumped)
```

This, however, does not seem to be dependent on the preset, because after restarting, I have tested the same preset again with no problems. It may be because I have so many presets installed; I have the community preset pack installed.

Please see attached core dump. I am not sure how useful it will be, because the binaries for this are long gone, Kodi has been upgraded several times since then. I have Kodi installed from the Packman repo.

-- Apologies - file too large to upload to GitHub, please find the core dump here:

https://www.dropbox.com/s/lqnmjvzl1pxxdis/core.kodi-x11.1000.edadd6d66b274fa8ba0012770538b54f.28524.1607945235000000.lz4?dl=0

**Comment by kblaschke** [comment]
Without the exact executable (including debug symbols) used to generate the core dump, it's rather useless as the memory addresses in the core dump can't be matched to anything. A crash backtrace is more useful in this case as it at lease gives away the call stack that lead to a crash.

There's a good chance this crash happens due to the C++-based API interface, where the plug-in and projectM C++ symbols don't exactly match. If you get this crash again, please reopen the issue with a stack trace. Otherwise, we sadly can't do anything else than guessing.
