### ISSUE TITLE
search for presets in source directory before installation location

### ISSUE THREAD

**Issue by Be-ing** [projectM-visualizer/projectm#497]
This would allow running projectM binaries from the build directory without needing to install them.

Mixxx does this by [searching for CMakeCache.txt](https://github.com/mixxxdj/mixxx/blob/f2d670edeb483efb066bf7f00255d01df2f0017c/src/preferences/configobject.cpp#L25) in the build directory and finding the path to the source tree from that. Optionally this can be overriden by the user with a command line argument. If neither the command line option is used nor CMakeCache.txt is found, then the application searches for data in the installed path (PROJECTM_DATADIR_PATH for projectM).

**Comment by kblaschke** [comment]
The hard coded preset path is definitely something worth reconsidering, especially as the path is derived from the install prefix. I'd personally prefer a default config file in the system config path where the path is read from, if no user config is available or the path has been overridden otherwise.

Any good recommendations on how to handle the data dir path in a more convenient and portable way are highly appreciated.

If you use the new CMake scripts, you can set `PROJECTM_DATADIR_PATH` to match the absolute value of `${CMAKE_SOURCE_DIR}/presets`, then the presets should be found.

**Comment by Be-ing** [comment]
I suggest to search a path relative to the location of the executable.

**Comment by revmischa** [comment]
The iTunes/Music.app plugin loads from its bundle https://github.com/projectM-visualizer/projectm/blob/master/src/projectM-MusicPlugin/iprojectM_mac.mm#L167
But it's not very portable or configurable

**Comment by kblaschke** [comment]
> I suggest to search a path relative to the location of the executable.

This would work fine for "dist" packages, meaning that the install directory has the same structure as the installed version. Depending on the platform, the layout is relatively fixed, so it really sounds like a good solution.

For running the application within the CMake build directory, this won't work at all times because with CMake, the build directory can exist anywhere, inside or outside the source tree. In this case I would suggest to add a command line argument (or env variable) which a developer can use to point to the preset and fonts directories. Most IDEs support run configurations and can set at least command line arguments.

Would that be a compromise?

**Comment by kblaschke** [comment]
> The iTunes/Music.app plugin loads from its bundle 
> But it's not very portable or configurable

Totally fine as for macOS, this is the way to go. Linux has the files in /use/share/projectM and Windows applications mostly put them under %PROGRAM_FILES%\projectM, just as the executable. So for creating OS packages, this would simply be a matter of creating a good layout in the install dir and making the relative location known to the executable.

I'd say there are two different things to consider:
1. How the defaults are set and configuration files are found and used in a user's installation,
2. Adding some way to directly run projectM-SDL from the build directory with source directory presets with no presets or configs installed on the system.

The latter point is only required for a very small group of people, actually those working directly with projectM sources, either standalone or as an integration. Can be done either via a cmdline argument as I stated in my previous comment or by setting a specific CMake variable to automatically add the source dir path to the list of preset search paths.

**Comment by kblaschke** [comment]
> Parse the CMakeCache.txt to get the path in this case.

As the executable or library has just been built with CMake, it'd be way easier to simply add a preprocessor define containing the source dir path instead of writing a full-blown CMakeCache.txt parser.

Also, the location of the executable inside the CMake build dir differs between platforms/generators, so you'd additionally need to traverse all parent directories to find it. IMO not really worth the effort and additional code.

Besides, pull requests are always welcome for this if you want to implement it yourself.

**Comment by kblaschke** [comment]
It's been a while now, and the CMake scripts are more mature. My suggestion to solve this in a way that doesn't require a lot of additional code and provide a good option for package maintainers would be to add a CMake option to set the default preset path to a fixed (absolute) path, e.g. `DEFAULT_PRESET_PATH`. Another option to always use this path and ignore the configuration could also be possible.

This way, developers can build debug executables using this default path to run the project and maintainers can use this to set the path to the actual install path of the resulting package (on Linux/macOS where paths normaly don't change).

Another solution (also in addition to the first one) would simpy be adding a command line parameter to either specify a different config file or override the preset path and other settings. This would in turn also help users to run projectM with different settings, but would only work in the SDL frontend, not other integrations.

**Comment by Be-ing** [comment]
I don't think compiling the path into the executable is a good idea. That would make it cumbersome for developers to test that the build system does installation right.

A command line option could work, but requiring developers to type that out is cumbersome. I still suggest using Mixxx's approach of locating the source directory by reading CMakeCache.txt and finding the path relative to that. Mixxx also supports overriding this with a command line option.

**Comment by kblaschke** [comment]
Some default path needs to be present in the case the user has no config file. Hard-coding this into libprojectM is definitely a bad idea, I concur.

The library should ideally not have any default paths, only some convenience methods to recursively search a given path for presets and add them to the playlist in the case the outside application doesn't want to take care of that (the API already allows to fill the preset playlist externally without using any built-in paths or scanning code).

Also, to locate the CMakeCache.txt the executable would need to know where to find it - so it needs another path to be compiled in or given as a parameter. The build dir structure itself is platform and build system dependent, so the projectMSDL executable can be created in different directories on different subdir levels - it's not a simple thing and adds more code than necessary.

I prefer the KISS principle here, making it possible to provide a custom preset dir to developers and users while not adding development-use-only code to the library. This would be either a command line parameter or possibly even an environment variable to make it independent of the actual application using projectM.

Also note that Mixxx uses Qt which provides a rich set of classes to do a lot of stuff, e.g. getting the application directory. While projectM is also a cross-platform library, it only uses the C++ standard library and some OpenGL-related APIs. The C++ standard library sadly has no filesystem support and no portable way to retrieve the executable path. This alone requires a few hundred lines of code to do on all supported platforms and might not even work properly if the library is used in a third-party app that has the presets elsewhere.

**Comment by Be-ing** [comment]
> The library should ideally not have any default paths, only some convenience methods to recursively search a given path for presets and add them to the playlist in the case the outside application doesn't want to take care of that (the API already allows to fill the preset playlist externally without using any built-in paths or scanning code).

So you think every application that uses libprojectM should ship its own presets? That doesn't seem like a great idea to me to put that burden on downstream application developers.

> The build dir structure itself is platform and build system dependent, so the projectMSDL executable can be created in different directories on different subdir levels - it's not a simple thing and adds more code than necessary.

That seems like a problem worth solving for its own sake.

> The C++ standard library sadly has no filesystem support and no portable way to retrieve the executable path. This alone requires a few hundred lines of code to do on all supported platforms and might not even work properly if the library is used in a third-party app that has the presets elsewhere.

:weary:

**Comment by kblaschke** [comment]
I don't say that all applications should ship their own presets. They can of course use anything projectM provides.

And that the files in the build dir are organized differently is nothing that either can or needs to be solved because each build system works differently and creates a custom directory structure. E.g. Visual Studio is a multi-configuration build system that will create an output directory for binaries per configuration, like Release and Debug, while the Makefile generator will place the executable one level above. Trying to fiddle with these paths always breaks stuff, I can tell from many years of experience.

In addition to that, projectM is basically a library, not an application (projectMSDL is one that happens to live in the same source tree for now). So the standard way of using it would be:

- Check out/download projectM
- Build projectM and install it somewhere
- Point your application's build dir to the projectM package and set include and library dirs, e.gm using CMake' find_package() command.
- Build the application and link libprojectM to it

In this scenario, you don't even have access to the original projectM source tree or the CMakeCache.txt in the build dir.

Also note that before the next release, the current repository will be split up into many smaller parts - see [the note in the 4.0 Release project](https://github.com/projectM-visualizer/projectm/projects/2#card-73223900). At this point, your suggestion won't work anymore at the latest.

**Comment by Be-ing** [comment]
> projectM is basically a library, not an application

Yeah, I think we may be talking about slightly different things. The problem I faced that led to opening this issue is that I built one of the example applications and it was unusable without installing it because it didn't find presets without running the installation step.

> Also note that before the next release, the current repository will be split up into many smaller parts - see the note in the 4.0 Release project. At this point, your suggestion won't work anymore at the latest.

I was just about to suggest doing this. That would allow downstream applications to include the presets as a submodule which could be included in Windows and macOS packages.

**Comment by kblaschke** [comment]
There's also always the option you fork the repo and implement any features you need there. If the work is done, you're welcome to create a pull request into the main repo and have the team review the changes. If the changes aren't too specific and can be useful for a wide range of projectM users, chances are good it'll be merged back into the main project repo.

**Comment by Be-ing** [comment]
That's a lot more work than running `cmake --install build`.

**Comment by kblaschke** [comment]
It is, exactly. See, we all do this in our free time at no pay, and if someone has a very specific problem/suggestion that possibly doesn't affect a lot of users or developers, and might even add maintenance cost (=more code) to the project, it's not something we (or any other OSS project) will just do upon request.

But here's the charm of OSS: you can change the code yourself, add features you need and even give back some of the work to the upstream project.

If you think it's too much work for you to add the suggested code for this feature on your own instead of installing projectM, then it's probably also not worth the effort for us to do it just for you.

**Comment by Be-ing** [comment]
Of course, I understand that. I thought you would also find this helpful for your own development workflow. Anyway, this is a moot point with the repository being split up.

**Comment by kblaschke** [comment]
There's still a valid point in regards to hard-coded paths being used and the lack of a way to specify a custom preset dir except via the config file.

I'll see what I can do about it while working through the to-do list. The rest will probably get more clear when the next release is nearing completion.
