### ISSUE TITLE
Texture loading: projectM loads all textures/images into VRAM on startup

### ISSUE THREAD

**Issue by OfficialIncubo** [projectM-visualizer/projectm#498]
I have added aprox. 25-40 HD textures to projectM. While I started the app on Android/Windows, it will take too long to load textures. It wastes my time. Can you fix this problem to load all the textures in a faster way?

**Comment by revmischa** [comment]
Sounds like a good area for improvement, I suggest you to profile that section of the code to find out why it is slow, optimize it, and open a pull request with your improvements

**Comment by kblaschke** [comment]
@Se7enSlasher Can you please provide one or more of those textures and the presets using them, if copyright allows?

Or at least give some specs about the textures like image dimensions, file sizes and compression algorithm used (JPG, PNG).

**Comment by Se7enSlasher** [comment]
Sorry for **LATE** response, but I can't attach the .zip file using my phone, so here is the link of my textures that I used: https://www.mediafire.com/download/e75gvwrm7gkfnfy
It contains +100 textures without using any compression software. Please don't view the full image. If you want to view them all, I am shame. The resolution of these images is 1280×720 and 1920×1080.
I am using preinstalled presets, but I added some of them that reads random texture code (I am also surprised with it 😀). I'll count 1000+ presets if I think of.... (sorry for my bad and incorrect language).
That's all. Hope it helps. 😉

**Comment by kblaschke** [comment]
Thanks, that'll make for a good test case!

The main with textures here is that projectM loads _all_ available textures on startup, no matter if they are used in any preset or not. This takes some time and also a good amount of VRAM, so some kind of "lazy load" feature might be useful. It's not easy to do though as presets have no explicit list of textures they use, especially if they're sampling them in shaders or even randomly as you stated. I see some ways of improvement here:

- Add some kind of "intelligent" detection logic that finds texture references in presets, then loads them in a separate thread before displaying the preset. This will not work for all presets though as mentioned above.
- Profile the loader and see if the code is simply too slow (currently projectM uses SpartanJ/SOIL2) and replace it with a faster implementation.
- Defer texture loading from disk/storage into a background thread, which might break some presets at the beginning, but improve startup time.
- Limit/scale down texture resolution to reduce GPU upload time and VRAM usage (which is _quite_ limited on mobile devices).

Also, always keep in mind that the file size of compressed images is way smaller than the VRAM they take up. A FullHD (1920x1080) texture takes up about 8 MiB of VRAM each, so if you have a hundred of them, that's 800 MiB VRAM - which is WAY more than most embedded or CPU-integrated GPUs have available in total.

**Comment by kblaschke** [comment]
Will at some point be fixed with issue #532 by only loading textures requested by the preset.

Besides that, adding huge textures will always add a performance impact due to time required for image loading. Milkdrop also suggests to only add textures up to 512x152 pixels to improve performance. Anything beyond that can't really be optimized by projectM.

**Comment by Se7enSlasher** [comment]
If the problem got solved, can I close it?

**Comment by kblaschke** [comment]
Sure.

The main issue, projectM loading _all_ textures on startup, isn't solved though. Ideally, only one or two textures, depending on what the preset requests, should be loaded at the time they are required, and ideally in a separate thread (including shader translation etc.). There's still a lot of work to do, but I'll eventually get to it after the new build system is stable.

If you could solve this specific issue here on your own, please feel free to close the case. The remaining work will still be done in the other issue, you can watch it to see any progress if you like.

**Comment by kblaschke** [comment]
Closed the missing textures issue linked above, as this loading problem here is out of scope and still needs fixing.

There's a [working branch](https://github.com/kblaschke/projectm/tree/lazy-texture-loading) in my fork where I started to rewrite the texture manager, but didn't really finish it yet due to other things being higher in the priority list for the 4.0 release.

This is what I'm going to do in the branch (some of those features are already partially implemented):
- Only load textures requested by a preset.
- Ideally, load the texture(s) in a separate thread (needs improving the "background worker" in class ProjectM so it can run over multiple frames instead of just a single pass, which doesn't do any good)
- Unload textures not used for a while, larger ones first.
- Improve random texture selection, e.g. do not use images with the same name as a preset file (thumbnail images).
- Make TextureManager more flexible so it can be fed with externally generated textures like noise and idle preset textures more easily, with a "keep indefinitiely" flag for some.

**Comment by kblaschke** [comment]
Most issues should be fixed with PR #716, specifically lazy texture loading, random texture selection and unloading unused textures after a while.

Other improvements like feeding textures from the outside application via callback will be implemented later, as they're out of scope here.
