### ISSUE TITLE
projectM - Android Auto/Apple CarPlay integration (support)

### ISSUE THREAD

**Issue by Se7enSlasher** [projectM-visualizer/projectm#506]
Is there a feature that integrates projectM to Android Auto or Apple CarPlay? Hope you like my idea/concept ;)

**Comment by Se7enSlasher** [comment]
I am gonna say a concept example:

It loads presets and textures from the phone while you open projectM for Android Auto/Apple CarPlay.

**Comment by kblaschke** [comment]
Since there's only a very basic Android example app in this repo and the Play Store version of projectM is not an open source project, there won't be any work happening on that from our end.

You can try contacting Peter Sperl via [the Play Store](https://play.google.com/store/apps/details?id=com.psperl.prjM&hl=de&gl=US) and request this feature for his app.
