### ISSUE TITLE
Hard Cut to Visualizations

### ISSUE THREAD

**Issue by LuisE2001** [projectM-visualizer/projectm#55]
Good Day
When I change to any other visualization than the principal, the program turns black, showing "Hard cut to ..." . What's the problem?

**Comment by revmischa** [comment]
Sorry, not familiar with that screen. Which app are you using?

**Comment by LuisE2001** [comment]
ProjectM PulseAudio Visualization
It appears down in the text bar and the screen turns black.

**Comment by LuisE2001** [comment]
![captura de pantalla de 2018-04-25 12-33-19](https://user-images.githubusercontent.com/30881863/39262394-de6fa8ca-4884-11e8-9d35-5f05d3e3c752.png)

**Comment by revmischa** [comment]
Wish I could help you but I don't know anything about the PA app. Sorry. Feel free to send in a PR!

**Comment by deltaoscarmike** [comment]
The preset "Aderrasi - Airs" fades to black and doesn't do anything else.
The problem is the preset, please try another one to confirm this.

**Comment by LuisE2001** [comment]
![captura de pantalla de 2018-04-26 21-34-14](https://user-images.githubusercontent.com/30881863/39341594-97185722-4999-11e8-88d9-b5b400c6fc50.png)
Everyone.

**Comment by deltaoscarmike** [comment]
Could you launch it from a console and paste here the output

**Comment by nuess0r** [comment]
The Problem is with the preset OR a combination of the preset and ProjectM.

I have the described behavior with a lot of presets when I just use the 'n' button (shortcut for hard-cut to next/random preset). When I open the menu and use the context menu (right click with the mouse on a preset) and select "Soft cut to this preset" the preset run fine and doesn't fade to black.

Unfortunately I didn't find any documentation about the difference between soft/hard cut and there is no shortcut for soft-cuts.
