### ISSUE TITLE
help installing on windows

### ISSUE THREAD

**Issue by oldcodewizard** [projectM-visualizer/projectm#571]
Hello

Thank you for'this great project! I just saw the youtube demo video.

I'm a complete beginner and want to install it in windows 10.

I found a file .tar.gz. But how to open/install this file in windows 10? What is the correct way of installing projectm in windows?

Thanks!

**Comment by chaosophy** [comment]
Hi,

There are several ways to use/install projectM...

Install from Steam...
https://store.steampowered.com/app/1358800/projectM_Music_Visualizer/

Install from Windows app store...
https://www.microsoft.com/en-gb/p/projectm/9ndcvh0vcwjn#activetab=pivot:overviewtab

Use github version.

github version is the latest version but there hasn't been a Windows build uploaded for a while, I also have no idea what version the Steam or Win app store versions are.

the last Windows build on here is v3.1.7...

https://github.com/projectM-visualizer/projectm/releases/tag/v3.1.7
https://github.com/projectM-visualizer/projectm/releases/download/v3.1.7/projectM-sdl-x64-win.zip

If you want a Windows build of the latest version - v3.1.12 - you'd need to download the source code and build the app yourself.

This - hopefully - should change with the next version v4.0.  A few of the guys on here (mainly kblaschke?) have been doing a lot of updates recently, fixing bugs and changing the build system for the app etc. but no idea on an eta.

tbh, for now - unless you want to build v3,1,12 - I'd probably just download the v3.1.7 version from here and use that until v4.0 hopefully posts here with a Windows build.

**Comment by kblaschke** [comment]
Yes, the latest Windows standalone build here is currently 3.1.7, can't really suggest to use it as it's old and unstable. The Steam version is decent (3.1.12) but still has some issues that are fixed in the source repo, but not yet released.

Easiest is using the Steam version, which also works fine without Steam running as it has no DRM or SteamAPI integration.

I've built a Windows version two weeks or so ago and released it here:
https://github.com/kblaschke/projectm/releases/tag/v3.1.13-9e8ab88-win64

There were still some more fixes/improvments since then. If you want to try a newer build, download the release above wich contains all DLLs and a decent directory structure to run projectM. Then go to the "[Actions](https://github.com/projectM-visualizer/projectm/actions)" tab above and select a recent build from the `master` branch. Download the "windows-latest" artifact on the bottom of the page, which is a ZIP file with the binaries. Only copy "projectMSDL.exe" from this archive and replace the one from the above ZIP and you've got a recent build.
