### ISSUE TITLE
Bump of license version

### ISSUE THREAD

**Issue by ErikPrantare** [projectM-visualizer/projectm#597]
As far as I know, there is no library that fulfills the same role and has the same features as the projectM library does. For these situations, the GNU project recommends using GPL, rather than LGPL: [Why you shouldn't use the Lesser GPL for your next library - GNU Project - Free Software Foundation](https://www.gnu.org/licenses/why-not-lgpl.html)

I propose that we bump the license from LGPLv2+ to AGPLv3+.

**Comment by kblaschke** [comment]
I strongly disagree, as this would mean that projectM cannot be used with _any_ closed-source application, not even as a plug-in, as the GPL requires the host application itself to be distributed under GPL. Besides requiring the OK from most if not all past contributors to change the license, it would drastically restrict the use of projectM. LGPL is enough to ensure the dev team could force anyone making closed-source changes to the library itself to publish the code.

Also, the AGPL isn't really required for this kind of project, as it's meant to prohibit companies to make changes to GPL'ed code and run it in their own servers without distributing the binaries to third parties. I can't really see a usecase where projectM would be affected by this.

Bumping the LGPL to v3 is possible though and we should do that at some point.

If you have a good argument why the AGPL would have huge benefits over the LGPL to both projectM users and developers, please feel free to comment, but closing the issue for now.

**Comment by ErikPrantare** [comment]
>I strongly disagree, as this would mean that projectM cannot be used with any closed-source application, not even as a plug-in, as the GPL requires the host application itself to be distributed under GPL.

Yes, that's a feature ;)

>Besides requiring the OK from most if not all past contributors to change the license [...]

LGPLv2.1+ allows relicensing under GPL, check the matrix: https://www.gnu.org/licenses/gpl-faq.en.html

>Also, the AGPL isn't really required for this kind of project, as it's meant to prohibit companies to make changes to GPL'ed code and run it on their own servers without distributing the binaries to third parties. I can't really see a usecase where projectM would be affected by this.

1: This is difficult to predict with the way the web is developing, and the AGPL doesn't create any issues that you wouldn't have in GPL.
2: Didn't this have an emscripten build? What's the point of that if not to make webapps?

>If you have a good argument why the AGPL would have huge benefits over the LGPL to both projectM users and developers, please feel free to comment, but closing the issue for now.

1: It would ensure that applications making use of this library are free, which I think is a worthy goal in and of itself. I generally don't like the idea of indirectly supporting proprietary developers. I would then give free labor for a cause I find unjust. End users will also rest assured that any software making use of the library also respects their freedom.

2: It allows the project to make use of other GPLed code. Distributing this project as GPL only increases our possibilites, rather than the reverse.

**Comment by ErikPrantare** [comment]
>cannot be used with any closed-source application, not even as a plug-in

Are you sure about this?

**Comment by kblaschke** [comment]
Yes, 100% sure, because the GPL explicitly forbids any linking to closed-source applications. That's the sole reason why LGPL exists, it explicitly exempts linking, if anyone can still replace the library or re-link the application against a self-compiled library.

Here's the relevant Q&A entry: https://www.gnu.org/licenses/gpl-faq#GPLInProprietarySystem
"Proprietary System" here refers to any kind of software or environment - a library, an application, a whole OS or an embedded device.

The AGPL is a more strict version of the GPL, as it has all of GPL's restrictions, plus the addition that changes made to AGPL software which are used in commercial applications like cloud services must also be published, which is not the case with GPL.

**Comment by ErikPrantare** [comment]
>However, in many cases you can distribute the GPL-covered software alongside your proprietary system. To do this validly, you must make sure that the free and nonfree programs communicate at arms length, that they are not combined in a way that would make them effectively a single program.

>The difference between this and “incorporating” the GPL-covered software is partly a matter of substance and partly form. The substantive part is this: if the two programs are combined so that they become effectively two parts of one program, then you can't treat them as two separate programs. So the GPL has to cover the whole thing.

>If the two programs remain well separated, like the compiler and the kernel, or like an editor and a shell, then you can treat them as two separate programs—but you have to do it properly. The issue is simply one of form: how you describe what you are doing. Why do we care about this? Because we want to make sure the users clearly understand the free status of the GPL-covered software in the collection.

This sounds like it still allows for plugins in my mind.

**Comment by ErikPrantare** [comment]
>The AGPL is a more strict version of the GPL, as it has all of GPL's restrictions, plus the addition that changes made to AGPL software which are used in commercial applications like cloud services must also be published, which is not the case with GPL.

Not just commercial, all cloud services. This doesn't cause an issue for free software, no? It simply fills a loophole that was in the GPL. If this isn't expected to be used in web environments, no loss, if it turns out to be, then it was a good choice to pick AGPL instead of just GPL ;)

**Comment by revmischa** [comment]
In general I would prefer LGPL or MIT or WTFPL license as it's more liberty for developers. I would rather see projectM code get more widely used even in commercial or non-free applications rather than restrict its circulation which doesn't benefit anyone. AGPL is a nuisance and we have to consider the fact we're also competing with similar libraries such as [Butterchurn](https://github.com/jberg/butterchurn)/[WebAmp](https://github.com/captbaritone/webamp) which are MIT licensed.

I am not clear on the "cause I find unjust" bit. It's a music visualizer for stoners to stare at. If anyone wants to take this code and make an application and charge money for it, more power to them! Hopefully they contribute back improvements they make, but if they don't, oh well. They weren't going to do that in the first place.

In any event I believe this conversation is moot because changing the license is not as simple as replacing LICENSE.TXT. We would need the sign-off of all contributors. If you want to contact all people who have contributed code over the past twenty years and get their approval then we can reopen this PR.

**Comment by revmischa** [comment]
Brother, I've sung the Share The Software song at CCC, I assure you I'm familiar with the FSF 😄 

![IMG_3304](https://user-images.githubusercontent.com/245131/159916813-3dbee718-46ce-480f-9fd0-efbef9e8ff52.JPG)

<img width="530" alt="Screen Shot 2022-03-24 at 12 31 29" src="https://user-images.githubusercontent.com/245131/159916711-bdf16bfd-ac18-4d82-9d7c-f8d377d6ffed.png">

**Comment by ErikPrantare** [comment]
Hell yes brother

**Comment by vikingsloth** [comment]
I'm glad I see people mentioning the linking aspect. This is a library and LGPL makes the most sense. Even if someone wrote some music player with an MIT license they would not be able to link to a GPL3 licensed library without making the entire thing GPL3. My thought is that if you do license this as GPL3 you will eventually end up with people forking the pre-GPL3 project and making their updates to the one they use. It would be better to have more people working on the same code base.

**Comment by kblaschke** [comment]
Foobar2000 is quite popular. And in the future, other applications might get projectM plug-ins. I don't see any good reason to limit the use of projectM to GPL-only host applications. The goal is to keep projectM open sourced and give users the ability to use their self-compiled projectM library/plug-in with those apps. The LGPL makes sure both is the case - at least as long as the app/plug-in author does it correctly and legally. If not - anyone can sue them to force them to do it right. There are precedents where this worked, good and bad alike (remember the [former kernel dev McHardy sueing companies](https://www.zdnet.com/article/linux-beats-internal-legal-threat/) to make some extra money?).

If you look at the new SDL2 frontend, I've chosen to put the new code under GPLv3 (the old SDL app was also LGPL-licensed). AGPL doesn't make sense as it's not something you could use as a server-side-only service for a commercial product.
