### ISSUE TITLE
Standalone Mac Installer Request 

### ISSUE THREAD

**Issue by samdonato** [projectM-visualizer/projectm#631]
**Is your feature request related to a problem? Please describe.**
I noticed there is no longer a standalone Mac installer. I tried to install brew, I can't find the application though. Can you make a standalone Mac installer for me? I'm running a M1 Mac. 
**Describe the solution you'd like**
Standalone Mac installer
**Describe alternatives you've considered**
This is the only thing like it.

**Comment by kblaschke** [comment]
We're surely planning to release a standalone version for macOS, but this will only have audio capture support via external microphones due to macOS API limitations.

Currently, the team has no Apple Developer account available to properly codesign the binaries. Running unsigned applications will result in a Gatekeeper warning on recent macOS versions, but they can still be installed. We might buy an annually renewed Developer ID subscription from the project funds in the future, so if you want to support us, this is the best way to do so. Click the "Sponsor" button above or directly head over to https://opencollective.com/projectm to donate.

If you want, you can already try the Apple Music visualization plug-in, which I've released in a development version here:

https://github.com/kblaschke/frontend-music-plug-in/releases/download/v3.0-pre1/ProjectM-MusicPlugin-3.0-pre1.pkg

It still has issues and will also give you a Gatekeeper warning, but it can visualize audio directly from the Music app.

To keep updated, you can follow our work in this repo and https://github.com/projectM-visualizer/frontend-sdl2, which is the new standalone end-user application we're preparing for release.
