### ISSUE TITLE
Settings menu for MacOS program?

### ISSUE THREAD

**Issue by Noisecomplaintz** [projectM-visualizer/projectm#651]
Hi, I was wondering if there was a settings menu or a way to select a specific preset? N for next, p for previous works, but is there a menu where I can look for specific presets and change other settings? It'd be great if someone could point me in the right direction. Thanks!

**Comment by kblaschke** [comment]
Normally, pressing M or return should open the preset selection menu. In the old releases, there's a certain range of versions which have a broken preset menu and other issues, so that might have hit you.

I can build an unsigned test release of the rewritten SDL app, which has those bugs fixed and working hotkeys on macOS. You can already find the source in this repo: https://github.com/projectM-visualizer/frontend-sdl2

I'll update this issue after I've created a dev release in my fork.

**Comment by kblaschke** [comment]
Please try this build here, it's unsigned and not a proper .app bundle, but it should run:

https://github.com/kblaschke/frontend-sdl2/releases/download/2.0-macos-pre1/projectMSDL.zip

Press F1 to display a help menu. To change settings, open the `projectMSDL.properties` file in a text editor and change the settings to your likings, the file is well documented.

**Comment by Noisecomplaintz** [comment]
> Please try this build here, it's unsigned and not a proper .app bundle, but it should run:
> 
> https://github.com/kblaschke/frontend-sdl2/releases/download/2.0-macos-pre1/projectMSDL.zip
> 
> Press F1 to display a help menu. To change settings, open the `projectMSDL.properties` file in a text editor and change the settings to your likings, the file is well documented. Some options can also be set via the command line. To see a list of options, please run the executable from a terminal with `./projectMSDL --help`.

Thank you very much! It works. Amazing! I'm very happy.

**Comment by kblaschke** [comment]
Glad to hear it works!
We'll release a proper app with icon and all at some point. Until then, I'll close this issue.
