### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by 486DX2** [projectM-visualizer/projectm#677]
Hi

I'm very new here.

Is this project the same as milkdrop in winamp?

Where csn I download more visualizations and how to install them? I use project m in my music player QMMP

THX
Lisa

**Comment by kblaschke** [comment]
Hi Lisa,

projectM is an open-source cross-platform reimplementation of Milkdrop using OpenGL instead of Direct3D to render the visuals. The project started in 2003, way before Milkdrop was open sourced. This, it still has lots of old "best-guess" code and is not (yet) fully compatible with all Milkdrop presets. We're actively working on it though!

If you want more presets, download this repository here (top right corner, the green button):

https://github.com/projectM-visualizer/presets-cream-of-the-crop

It has over 9000 selected and sorted presets. This pack is also the default one shipping in future projectM releases.

If you really want a huge number of presets, Mischa provides a huge 40k+ collection of almost all presets ever released here:

https://mischa.lol/projectM/presets_community.zip

**Comment by 486DX2** [comment]
Hi

Thanks, wow so many!!!

I still have 3 questions:

- does the 2nd file ( 40k+) also has all the presets of the first file ( 9000)?
- is the milkdrop code being used for project M now too?
- so not all winamp preset will work in current version?

**Comment by kblaschke** [comment]
1. Hard to say, they were created by different people from different sources. But the 40k pack will contain a large number of the 9k pack.
2. Not directly, since Milkdrop is using DirectX and other Windows API functionality. We're using the published code as a reference to improve compatibility though.
3. Exactly, they may just look slightly different or can be completely broken. There's still a number of issues like missing features and other bugs, plus projectM needs to translate DirectX GPU shaders to OpenGL, which isn't straightforward and in some cases impossible without manually rewriting the presets.

**Comment by 486DX2** [comment]
Sorry I have many questions :-D
I'm using the presets also in QMMP https://qmmp.ylsoftware.com/
In the readme of that player you can read it uses Project M version 2.1.0 
Some presets behave weird or display in the corner of the screen a not very much moving small thing. I think it can't be the purpose of this preset.
Does this mean the Project M version is too old for those presets?

Why don't projects like QMMP update its project M?

**Comment by kblaschke** [comment]
projectM is just a library, and this is used by other devs as they see fit. It often happens someone writes an integration for a player like QMMP, but then the original author of the integration stops working on it and no one takes over the maintenance.

Regarding this player, you'd have to direct the question to the community of this software. Here, we only develop the core visualizer library and a few example/reference applications to show how the library can be used.

If you've got more questions, I suggest to join our Discord server. It's easier to chat there than using the bug tracker.

https://discord.gg/TFZEVM88

You find me there with the handle CodAv#0175.
