### ISSUE TITLE
Command Flags not working in homebrew version

### ISSUE THREAD

**Issue by T-31** [projectM-visualizer/projectm#710]
- Application: projectMSDL (installed with brew)
 - OS: macOs Ventura 13.1
 - Version 3.1.12

In the homebrew version, command flags are not working, thus not being able to provide a preset at program start.

When I try to start it using a preset (using _-p_ or _--presetPath_) I get this error:
`UNSUPPORTED (log once): POSSIBLE ISSUE: unit 0 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable`

The _--help_ flag isn't working either.

<img width="1069" alt="Bildschirm­foto 2023-03-22 um 23 25 18" src="https://user-images.githubusercontent.com/94144692/227052432-eac76b0e-fd53-40a6-ac3b-ba1bee03b680.png">

**Comment by kblaschke** [comment]
The Homebrew version is the old SDL application, which doesn't have any command-line parameters. The error you see shouldn't prevent projectM from working, it's rather a followup issue because it can't find any textures.

Until we can update the Homebrew formula, you can give my development build from last year a try, which is more recent than what Homebrew provides, plus it's a universal binary:

https://github.com/kblaschke/frontend-sdl2/releases/tag/2.0-macos-pre1

**Comment by T-31** [comment]
thanks a lot!

**Comment by kblaschke** [comment]
Closing as it's about an old version. For now, better not use the brew version until it's been updated. We're looking into options on how to do that.
