### ISSUE TITLE
projectm_set_preset_switch_requested_event_callback (almost) stops automatic preset switching

### ISSUE THREAD

**Issue by Jonathhhan** [projectM-visualizer/projectm#854]
### Please confirm the following points:

- [X] This report is NOT about the Android apps in the Play Store
- [X] I have [searched the project page](https://github.com/search?q=org%3AprojectM-visualizer+type%3Aissue+&type=issues) to check if the issue was already reported

### Affected Application

Third-Party Integration (Kodi, VLC, etc. - please specify below)

### Affected Version

4.1.0

### Operating System

Other, all or not relevant

### Additional Application Details

I use projectM with an addon for Open Frameworks. Tested with Linux and Windows.

### Type of Defect

Other

### Describe the Issue

I thought the callback is just for getting notification, when a preset switches. But it seems, that it also affects the preset switching (it almost stops switching). I think, I implemented the callback correctly, because if a pattern rarely switches (automatically) I get a callback.

**Comment by kblaschke** [comment]
I guess there's a slight misunderstanding on how these callbacks work. We should probably add some additional documentation in the API docs to state this more clearly. Until then, here's a short summary on how these calls are meant to be used.

The core projectM library supports these two callbacks:
- `projectm_preset_switch_requested_event`: projectM requesting a preset switch (after the preset display time is up)
- `projectm_preset_switch_failed_event`: Notifying the application that a preset couldn't be loaded

The switch requested event is only called _once_ after each preset is loaded, when the set display time is up. The application can then decide to switch to a new preset or keep the current one. In the latter case, no further preset switch events will be sent until the application loads a new preset. The core library does _never_ load a new preset on its own, which is a change from the 3.x series. It no longer keeps an internal playlist.

The failed event will be called immediately when loading a new preset form a file or string if the load fails, e.g. due to invalid expressions, parsing or file access errors. This way, applications can choose to try another preset, or display the error to the user, e.g. in case this is done by a preset editor UI or similar.

If you want to have projectM keep a playlist and switch presets automatically without implementing this yourself, please takea  look at the optional [playlist library](https://codav.de/projectM-API/playlist_8h.html) that is built alongside the core projectM library. The playlist library is a small wrapper around the above mentioned callbacks, allowing to manage a simple playlist and automate preset switching. The playlist library provides the ["preset switched" callback](https://codav.de/projectM-API/playlist__callbacks_8h.html#a8b287c054310ff48663fdab69d164856) you probably expected.

Here's a summary of what the playlist library provides:
- Wraps the two callbacks of the core core library and provides higher-level post-switch events for both success and failure.
- You can add single presets or recursively load whole directories to the playlist at once.
- You can edit existing playlists, removing and adding presets anywhere.
- You can filter playlists using glob patterns.
- Supports random or ordered playback and jumping to a specific index.
- Keeps a playback history of up to 1000 presets, including a "go back" function.

The playlist library has been kept simple, mainly acting as a replacement for the core functionality provided in previous releases, plus a few quality-of-life additions. For most use cases, it should work just fine. You can also look at [the implementation](https://github.com/projectM-visualizer/projectm/tree/master/src/playlist) to get an idea of how it works, in case you want to implement it yourself.

**Comment by Jonathhhan** [comment]
@kblaschke thanks a lot for the explanations, I have a better understanding now and `projectm_playlist_set_preset_switched_event_callback()` seems what I was looking for (I already use the playlist lib).

**Comment by kblaschke** [comment]
I'll close this issue then, as it's all there.

We'll improve the docs - both API and Wiki - as it's definitely not stated clearly enough how the playlist library interacts with the core library in regards to callbacks.
