### ISSUE TITLE
[FEATURE] disable idlePreeset

### ISSUE THREAD

**Issue by Jonathhhan** [projectM-visualizer/projectm#855]
### Please confirm the following points:

- [X] This feature request is NOT for the Android apps in the Play Store
- [X] I have [searched the project page](https://github.com/search?q=org%3AprojectM-visualizer+type%3Aissue+&type=issues) to check if a similar request was already made

### Application or Project

I don't know / Multiple / Other (please elaborate below)

### Is Your Enhancement Related to a Problem?

No.

### Your Suggested Enhancement

Right now I skip the idlePreset with `projectm_playlist_play_next(projectMPlaylistHandle, true);` at startup. I wonder, if there is a way to disable it. Something like `projectm_playlist_disable_idlepreset` or if it would make sense to implement it?

### Alternative Solutions

Right now I skip the idlePreset with `projectm_playlist_play_next(projectMPlaylistHandle, true);` at startup.

### Additional Context

Not sure, if it is needed. Can still use the alternative solution.

**Comment by Jonathhhan** [comment]
Find a good alternative and close this issue: `projectm_playlist_set_position(projectMPlaylistHandle, ofRandom(0, projectm_playlist_size(projectMPlaylistHandle) - 1), true);`

**Comment by kblaschke** [comment]
Yes, that's one way. You could also enable shuffle and then call the play_next method for example.
The idle preset is loaded by projectM on startup, and the playlist library doesn't load anything new when connected to the projectM instance, that's why you need to manually perform a switch.

I thought about this some time while implementing it, and then decided this way. Not changing the active preset when connecting a playlist manager enables applications to smoothly switch between different playlists, keeping the current preset playing until the next switch, which would then use a preset from the new playlist.
